### ISSUE TITLE
Update Tangram ES examples

### ISSUE THREAD

**Issue by nvkelso** [tangrams/cartography-docs#27]
In the setting an API key example we show an older version of a updating the Tangram scene after import to override a global value. New Tangram ES have different syntax, and allow chaining modifications together.

This is a better example for newer Tangram ES:

```
map->loadScene(
    "https://mapzen.com/carto/refill-style/6/refill-style.yaml",
    false,
    { SceneUpdate("global.sdk_mapzen_api_key", "mapzen-xxxxxx"),
      SceneUpdate("global.sdk_building_extrude:", "false") }
);
```

While previously we stated:

```
map->loadScene(
    "https://mapzen.com/carto/refill-style/6/refill-style.yaml",
    false,
    { "global.sdk_mapzen_api_key", "mapzen-xxxxxx" }
);
```

Which wasn't _wrong_, but the updated syntax allows chaining the globals.

**Comment by nvkelso** [comment]
This newer syntax has been around since Tangram ES [0.4.9-android](https://github.com/tangrams/tangram-es/releases/tag/0.4.9-android) so don't think we need to clarify versions in the docs.

Should split the example code into just the API key, and then showing how to chain multiple globals together in the lower sections.

**Comment by tallytalwar** [comment]
Whats currently there in the docs will actually not compile for tangram-es!

**Comment by nvkelso** [comment]
Fixed in https://github.com/tangrams/cartography-docs/pull/40.

**Comment by nvkelso** [comment]
Fix is live, closing. 

(Screenshot below)

<img width="718" alt="screen shot 2017-10-23 at 14 02 43" src="https://user-images.githubusercontent.com/853051/31913059-e241e384-b7fa-11e7-961d-720fe3365a87.png">

**Comment by matteblair** [comment]
The specific syntax for this is going to vary depending on the platform where you're using Tangram ES. The syntax in that last screenshot is what you would if you were using the C++ interface directly, not what you would use for Android or iOS (which is probably most users). It may be easier and more useful to just link to the relevant documentation for the Tangram ES mobile platforms.

**Comment by nvkelso** [comment]
What’s the documentation link to use?

**Comment by matteblair** [comment]
Or maybe we can show the Tangram ES code for both iOS and Android, since this section has several examples already.

**Comment by nvkelso** [comment]
@matteblair Both work for me, if you provide the snippets and links :)

**Comment by matteblair** [comment]
This would look like..

On Android, with a `MapController` object named `mapController`:
```
mapController.loadSceneFileAsync(
    "https://mapzen.com/carto/refill-style/6/refill-style.yaml",
    Arrays.asList(new SceneUpdate("global.sdk_mapzen_api_key", "mapzen-xxxxxx")
);
```
On iOS, from your `MapViewControllerDelegate`:
```
[super loadSceneAsyncFromURL:[NSURL URLWithString:@"https://mapzen.com/carto/refill-style/6/refill-style.yaml"]
                 withUpdates:@[[[TGSceneUpdate alloc]initWithPath:@"global.sdk_mapzen_api_key" value:@"mapzen-xxxxxx"]]];
```
