### ISSUE TITLE
Update docs for Zinc theme in Cinnabar style

### ISSUE THREAD

**Issue by nvkelso** [tangrams/cartography-docs#33]
- Remove Zinc from Basemap styles page (fine to add note under Cinnabar for redirection). Copy what Refill did, with single URL instead of all the label variants.
- In Themes page add new Cinnabar section, with a Color section and a labels section. This is a little heavy handed, but until all styles have each of these options it's probably better to be explicate.
- In the Icons big table remove the duplicate Zinc column (it's off screen, didn't you know!) @nvkelso

**Comment by sensescape** [comment]
https://github.com/tangrams/cartography-docs/pull/35

**Comment by nvkelso** [comment]
Completed
