### ISSUE TITLE
Update docs for icon library examples

### ISSUE THREAD

**Issue by nvkelso** [tangrams/cartography-docs#34]
The table of all the icons should still be good... but we're publishing an update for official support for mapzen_icon_library imports and the following sections need updating:

- Using built-in sprites
- Using Mapzen icons independently (move above the table of icons). Most of this content can be deleted, it's only the import that is unique over the `Using built-in sprites` example.
- Update version numbers (increment major number – if it was 5 then it's 6 now)
- At the bottom of the Icons page in the Versions section add "and later":
    - example: Bubble Wrap: `6.0.0` and later

Both should reference `mapzen_icon_library` as the style name (not `icons`).

**Comment by nvkelso** [comment]
- https://github.com/tangrams/refill-style/pull/67/files
- https://github.com/tangrams/cinnabar-style/pull/43
- https://github.com/tangrams/bubble-wrap/pull/254
- https://github.com/tangrams/tron-style/pull/151
- https://github.com/tangrams/walkabout-style/pull/190
   - This one needs to propagate to more-labels and no-labels – propose just moving those files into the main repo and marking the other ones dead

**Comment by sensescape** [comment]
https://github.com/tangrams/cartography-docs/pull/35

**Comment by nvkelso** [comment]
Completed.
